[minor] exception thrown when handing error for cluster management addon does not exist
```
TypeError: Value of unknown type: <class 'kubernetes.dynamic.exceptions.NotFoundError'>, 404
```

Signed-off-by: Hao Liu <haoli@redhat.com>